support guard templates
datarobot-community/datarobotx-idp pull request #46
Opened 2024-05-26 22:06 UTC by derluke

## Summary

Support guard templates on custom model versions

## Rationale

### Note: This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, etc.

2024-05-30 12:58 UTC, mpkrass7 commented on .vscode/settings.json
> +    "editor.formatOnSave": false,
Remove file

2024-05-30 13:00 UTC, mpkrass7 requested changes
I don't know enough about guard stuff to give a thorough review but I can at least say you should delete two files from here

2024-05-30 13:32 UTC, derluke commented
> I don't know enough about guard stuff to give a thorough review but I can at least say you should delete two files from here

ugh - I thought I did. sry

2024-05-30 15:57 UTC, brau0300 requested changes

2024-05-30 15:57 UTC, brau0300 commented on tests/integration/test_guard_configurations.py
> +    assert len([gc for gc in guard_config if guard_template_name_toxicity in gc["name"]]) == 1
think we should assert that the requested mutation to the intervention is also present server side here

2024-05-30 15:57 UTC, brau0300 commented on src/datarobotx/idp/guard_configurations.py
> +def get_or_create_guard_config_to_custom_model_version(  # noqa: PLR0913
i found this name a bit unclear - any ideas for alternatives?
maybe:
get_or_create_custom_model_version_with_guard_config

2024-05-30 15:57 UTC, brau0300 commented on src/datarobotx/idp/guard_configurations.py
> +    """Add a guard configuration to a custom model version.
Was assuming this would be something like "Get or create a custom model version with the requested guard configuration."

2024-05-30 15:57 UTC, brau0300 commented on src/datarobotx/idp/guard_configurations.py
> +def get_update_or_create_guard_config_to_custom_model_version(  # noqa: PLR0913
similar to above, i found this name a bit unclear - any ideas for alternatives?
maybe:
get_update_or_create_custom_model_version_with_guard_config

2024-05-30 15:57 UTC, brau0300 commented on src/datarobotx/idp/guard_configurations.py
> +    if endpoint is not None and token is not None:
this can be simplified since endpoint, token are required

2024-05-30 16:16 UTC, derluke commented on src/datarobotx/idp/guard_configurations.py
> +    name : Optional[str], optional
and does description need to be in the hash?

2024-05-31 02:38 UTC, brau0300 approved these changes
two minor comments - otherwise looks great

2024-05-31 02:38 UTC, brau0300 commented on src/datarobotx/idp/guard_configurations.py
> +def _get_unfrozen_model_version_id(
maybe rename _get_or_create... for clarity, i was initially confused when reviewing the calling function until i read the source for this function

2024-05-31 02:38 UTC, brau0300 commented on tests/integration/test_guard_configurations.py
> +def test_get_or_create_guard_config_to_custom_model_version(
minor: suggest renaming the two test functions to better align to the new helper names

2024-06-03 22:37 UTC, closed without merging