Remove kwargs from dataset creation (file and dataframe)
datarobot-community/datarobotx-idp pull request #49
Opened 2024-06-04 17:08 UTC by mpkrass7

Kwargs are currently only used in the hash funcion in two of our public helpers. They should not be in the function signature

## Summary

## Rationale

### Note: This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, etc.

2024-06-04 17:55 UTC, brau0300 approved these changes
just confirming that the underlying official client methods don't have any additional arguments

2024-06-08 13:33 UTC, derluke commented
I had discussed with Marshall. we should keep the **kwargs - but ensure that args like `max_wait` or `timeout` are pulled ignored in the hash. Same is true for many other helpers.
![image](https://github.com/datarobot-community/datarobotx-idp/assets/6739699/e7d38216-8317-4985-90fc-7d9cc8d5ae47)

2024-06-08 13:37 UTC, derluke requested changes
keep **kwargs, but pull out immaterial args for hashing

2024-06-11 13:12 UTC, mpkrass7 commented
@j-beastman to our discussion about hash kwargs vs rest of kwargs, I'm assigning this guy to you

2024-08-20 12:36 UTC, closed without merging